defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


name: Twilight Courier
title: Twilight Courier
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  VJ_Demos:
    output: true
    order_n: 4
    added_text: 1
  Tutorials:
    output: true
    order_n: 3
  Online_Course:
    output: true
    order_n: 1     
  Web_Design:
    output: true
    order_n: 6
  Event_Articles:
    output: true
    order_n: 2
  events:
    output: true
  Video_Tests:
    output: true
    added_text: 1
    order_n: 5  
        
  

collections_dir: collections_content_