defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


name: Twilight Courier
title: Twilight Courier
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  VJ_Demos:
    output: true
    order_n: 7
    added_text: 1 
  Video_Tests:
    output: true
    order_n: 5
    added_text: 1   
  Event_Videos:
    output: true
    order_n: 6
    added_text: 1         
  Tutorials:
    output: true
    order_n: 8
  Online_Course:
    output: true
    order_n: 10     
  Web_Design:
    output: true
    order_n: 4
  Event_Articles:
    output: true
    order_n: 9
  events:
    output: true

        
  

collections_dir: collections_content_